In [38]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import cv2

In [39]:
plt.style.use('seaborn')

In [40]:
data=pd.read_csv('train.csv')
df=np.array(data)

In [41]:
labels=[]
m=df.shape[0]
print(m)
for i in range(m):
    labels.append(df[i][1])
#print(labels)

304


In [42]:
datapath='Images/'
def create_data(df):
    m=df.shape[0]
    X=[]
    for i in range(m):
       # print(datapath+df[i][0])
        img=cv2.imread(datapath+df[i][0])
        img=cv2.resize(img,(300,300))
        X.append(img)
    return X

In [43]:
X=create_data(df)

In [44]:
X=np.array(X)
print(X.shape)

(304, 300, 300, 3)


In [45]:
X=X.reshape((X.shape[0],-1))

In [46]:
print(X.shape)

(304, 270000)


In [47]:
def normalize(X):
    m=X.shape[0]
    for i in range(m):
        u=np.mean(X[i])
        sigma=np.std(X[i])
        X[i]=(X[i]-u)/sigma
    return X

In [48]:
X=normalize(X)

In [49]:
print(X)

[[  1   0   0 ...   0   0 255]
 [  0   0   0 ...   0   0   0]
 [  0   0   0 ...   0   0   0]
 ...
 [  0   0   0 ...   0   0   0]
 [  0   0   0 ...   0   0   0]
 [  0   0   0 ...   0   0   0]]


In [50]:
from sklearn import svm

In [51]:
svm_classifier=svm.SVC(kernel='linear',C=1.0)

In [52]:
svm_classifier.fit(X,labels)
svm_classifier.score(X,labels)

1.0

In [53]:
test_data=pd.read_csv('test.csv')
test=np.array(test_data)

In [54]:
dp='Images_test/'
def create_data(test):
    n=test.shape[0]
    x=[]
    for i in range(n):
        t_img=cv2.imread(dp+test[i][0])
        t_img=cv2.resize(t_img,(300,300))
        x.append(t_img)
    return x

In [55]:
x=create_data(test)

In [56]:
x=np.array(x)

In [57]:
x.shape

(123, 300, 300, 3)

In [58]:
x=x.reshape((x.shape[0],-1))

In [59]:
x.shape

(123, 270000)

In [60]:
x=normalize(x)

In [61]:
print(x)

[[  1   1   1 ...   1   1   1]
 [  0   0   0 ...   0   0   0]
 [  1   1   1 ...   1   1   1]
 ...
 [  0   0   0 ...   0   0   0]
 [255   0 254 ... 255   1   0]
 [  1   1   1 ...   1   1   1]]


In [62]:
lab=svm_classifier.predict(x)

In [63]:
print(lab)
import csv
with open('poke.csv','w',newline='') as csvFile:
    writer=csv.writer(csvFile)
    n=test.shape[0]
    writer.writerow(['ImageId','NameOfPokemon'])
    for i in range(n):
        l=[test[i][0],lab[i]]
        writer.writerow(l)
    csvFile.close()

['Bulbasaur' 'Charmander' 'Bulbasaur' 'Charmander' 'Bulbasaur' 'Bulbasaur'
 'Charmander' 'Bulbasaur' 'Bulbasaur' 'Charmander' 'Bulbasaur' 'Bulbasaur'
 'Bulbasaur' 'Bulbasaur' 'Charmander' 'Pikachu' 'Charmander' 'Charmander'
 'Pikachu' 'Charmander' 'Pikachu' 'Bulbasaur' 'Charmander' 'Bulbasaur'
 'Pikachu' 'Charmander' 'Bulbasaur' 'Bulbasaur' 'Pikachu' 'Pikachu'
 'Charmander' 'Bulbasaur' 'Charmander' 'Bulbasaur' 'Charmander'
 'Bulbasaur' 'Bulbasaur' 'Bulbasaur' 'Charmander' 'Bulbasaur' 'Bulbasaur'
 'Charmander' 'Bulbasaur' 'Charmander' 'Charmander' 'Bulbasaur'
 'Charmander' 'Bulbasaur' 'Charmander' 'Charmander' 'Bulbasaur'
 'Charmander' 'Bulbasaur' 'Bulbasaur' 'Charmander' 'Bulbasaur'
 'Charmander' 'Bulbasaur' 'Pikachu' 'Charmander' 'Charmander' 'Pikachu'
 'Charmander' 'Charmander' 'Pikachu' 'Bulbasaur' 'Bulbasaur' 'Pikachu'
 'Charmander' 'Bulbasaur' 'Pikachu' 'Bulbasaur' 'Bulbasaur' 'Bulbasaur'
 'Charmander' 'Charmander' 'Charmander' 'Charmander' 'Bulbasaur'
 'Bulbasaur' 'Pikachu' 'Bulb